### ISSUE TITLE
Where(Ex{}) causes panics [mysql]

### ISSUE THREAD

**Issue by dabfleming** [doug-martin/goqu#49]
I realize this is probably not quite the intended usage, but it's something I ran into and it does seem that goqu should throw an error or ignore empty input rather than causing a panic here.

```
ex := goqu.Ex{}
if somethingFalse {
    ex["foo"] = bar
}
var things []Thing
// Following line causes panic in goqu code
err := db.From("tablename").Where(ex).ScanStructs(&things)
```

Somewhat redacted/modified panic output:
```
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 20 [running]:
testing.tRunner.func1(0xc4200b82d0)
	/usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0x14ec0a0, 0x1876e70)
	/usr/local/go/src/runtime/panic.go:491 +0x283
gopkg.in/doug-martin/goqu%2ev4.(*DefaultAdapter).ExpressionListSql(0xc420194d80, 0xc420182360, 0x1843420, 0xc42016ce20, 0x0, 0x0)
	gopath/src/gopkg.in/doug-martin/goqu.v4/default_adapter.go:935 +0x281
gopkg.in/doug-martin/goqu%2ev4.(*Dataset).expressionSql(0xc42017eea0, 0xc420182360, 0x183f000, 0xc42016ce20, 0xc42016ce20, 0x1)
	gopath/src/gopkg.in/doug-martin/goqu.v4/dataset.go:291 +0x9f0
gopkg.in/doug-martin/goqu%2ev4.(*Dataset).Literal(0xc42017eea0, 0xc420182360, 0x15437e0, 0xc42016ce20, 0x0, 0x0)
	gopath/src/gopkg.in/doug-martin/goqu.v4/dataset.go:211 +0x64c
gopkg.in/doug-martin/goqu%2ev4.(*DefaultAdapter).Literal(0xc420194d80, 0xc420182360, 0x15437e0, 0xc42016ce20, 0x0, 0x0)
	gopath/src/gopkg.in/doug-martin/goqu.v4/default_adapter.go:333 +0x4d
gopkg.in/doug-martin/goqu%2ev4.(*DefaultAdapter).ExpressionMapSql(0xc420194d80, 0xc420182360, 0xc42018ac90, 0x0, 0x0)
	gopath/src/gopkg.in/doug-martin/goqu.v4/default_adapter.go:1054 +0x73
gopkg.in/doug-martin/goqu%2ev4.(*Dataset).expressionSql(0xc42017eea0, 0xc420182360, 0x183ee00, 0xc42018ac90, 0xc42018ac90, 0x1543801)
	gopath/src/gopkg.in/doug-martin/goqu.v4/dataset.go:317 +0x518
gopkg.in/doug-martin/goqu%2ev4.(*Dataset).Literal(0xc42017eea0, 0xc420182360, 0x151aee0, 0xc42018ac90, 0x2da01053a78, 0x0)
	gopath/src/gopkg.in/doug-martin/goqu.v4/dataset.go:211 +0x64c
gopkg.in/doug-martin/goqu%2ev4.(*DefaultAdapter).Literal(0xc420194d80, 0xc420182360, 0x151aee0, 0xc42018ac90, 0x0, 0x1)
	gopath/src/gopkg.in/doug-martin/goqu.v4/default_adapter.go:333 +0x4d
gopkg.in/doug-martin/goqu%2ev4.(*DefaultAdapter).ExpressionListSql(0xc420194d80, 0xc420182360, 0x1843420, 0xc42016cd80, 0x0, 0x0)
	gopath/src/gopkg.in/doug-martin/goqu.v4/default_adapter.go:935 +0xe6
gopkg.in/doug-martin/goqu%2ev4.(*Dataset).expressionSql(0xc42017eea0, 0xc420182360, 0x183f000, 0xc42016cd80, 0xc42016cd80, 0x1)
	gopath/src/gopkg.in/doug-martin/goqu.v4/dataset.go:291 +0x9f0
gopkg.in/doug-martin/goqu%2ev4.(*Dataset).Literal(0xc42017eea0, 0xc420182360, 0x15437e0, 0xc42016cd80, 0x7, 0x7)
	gopath/src/gopkg.in/doug-martin/goqu.v4/dataset.go:211 +0x64c
gopkg.in/doug-martin/goqu%2ev4.(*DefaultAdapter).Literal(0xc420194d80, 0xc420182360, 0x15437e0, 0xc42016cd80, 0x7, 0x0)
	gopath/src/gopkg.in/doug-martin/goqu.v4/default_adapter.go:333 +0x4d
gopkg.in/doug-martin/goqu%2ev4.(*DefaultAdapter).WhereSql(0xc420194d80, 0xc420182360, 0x1843420, 0xc42016cd80, 0x0, 0x0)
	gopath/src/gopkg.in/doug-martin/goqu.v4/default_adapter.go:580 +0xce
gopkg.in/doug-martin/goqu%2ev4.(*Dataset).selectSqlWriteTo(0xc42017f200, 0xc420182360, 0x0, 0x18a7170)
	gopath/src/gopkg.in/doug-martin/goqu.v4/dataset_select.go:385 +0x18e
gopkg.in/doug-martin/goqu%2ev4.(*Dataset).ToSql(0xc42017f200, 0xc420053e08, 0x1, 0x1, 0xc42017f200, 0xc42016cd80, 0xc4201982e0, 0x1)
	gopath/src/gopkg.in/doug-martin/goqu.v4/dataset_select.go:358 +0xe1
gopkg.in/doug-martin/goqu%2ev4.(*Dataset).ScanStructs(0xc42017f0e0, 0x1499a80, 0xc42016cd20, 0x1, 0xc42017f0e0)
	gopath/src/gopkg.in/doug-martin/goqu.v4/dataset_actions.go:13 +0x53
```

**Comment by aviddiviner** [comment]
Also encountered this same error today.

**Comment by aviddiviner** [comment]
Okay, I've got a bit more context on how to reproduce this which may help with debugging. It has nothing to do with `ScanStructs`, as you'll see the stacktrace is failing in `ToSql`.

Here's what I've found:
```go
filters := goqu.Or()
filters.Append(
	goqu.I("name").Eq("a"),
)
filters.Append(
	goqu.I("name").Eq("b"),
)

db.From("table").Where(filters).ToSql() // this fails
```
```go
filters := goqu.Or(
	goqu.I("name").Eq("a"),
)
filters.Append(
	goqu.I("name").Eq("b"),
)

db.From("table").Where(filters).ToSql() // this passes
```
HTH

**Comment by aviddiviner** [comment]
While I'm at it, might I also suggest that `goqu.Or` and `goqu.And` should both return an `ExpressionList` (interface) instead of the private `expressionList` struct. Because they return different types, this will fail:

```go
filters := goqu.And(...)
filters = filters.Append(...)
```
because of the differing types.
