### ISSUE TITLE
Test suite fails to run

### ISSUE THREAD

**Issue by cmoad** [doug-martin/goqu#63]
The test suite throws an error under golang 1.10.3 on OSX.

```
☁  goqu.v4 [master] ⚡  ./go.test.sh
--- FAIL: TestScanStruct (0.00s)
panic: reflect: reflect.Value.Set using value obtained using unexported field [recovered]
	panic: reflect: reflect.Value.Set using value obtained using unexported field

goroutine 10 [running]:
testing.tRunner.func1(0xc42012e3c0)
	/usr/local/Cellar/go/1.10.3/libexec/src/testing/testing.go:742 +0x567
panic(0x15c2760, 0xc4203665d0)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x24a
reflect.flag.mustBeAssignable(0x1d6)
	/usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:231 +0x23c
reflect.Value.Set(0x15af440, 0xc420116a80, 0x1d6, 0x15af440, 0xc420116aa0, 0x16)
	/usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:1367 +0x3d
gopkg.in/doug-martin/goqu%2ev4.initEmbeddedPtr(0x160ee20, 0xc420116a80, 0x199)
	/Users/charlie/Source/gopath/src/gopkg.in/doug-martin/goqu.v4/crud_exec.go:327 +0x281
gopkg.in/doug-martin/goqu%2ev4.assignVals(0x15af4c0, 0xc420116a80, 0xc4200ac1d8, 0x1, 0x1, 0xc420268ae0, 0x0, 0x1)
	/Users/charlie/Source/gopath/src/gopkg.in/doug-martin/goqu.v4/crud_exec.go:281 +0x196
gopkg.in/doug-martin/goqu%2ev4.CrudExec.scanContext(0x16cce80, 0xc420268960, 0x165a5cf, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, 0x16ca300, ...)
	/Users/charlie/Source/gopath/src/gopkg.in/doug-martin/goqu.v4/crud_exec.go:270 +0xa6c
gopkg.in/doug-martin/goqu%2ev4.CrudExec.ScanStructContext(0x16cce80, 0xc420268960, 0x165a5cf, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, 0x16ca300, ...)
	/Users/charlie/Source/gopath/src/gopkg.in/doug-martin/goqu.v4/crud_exec.go:117 +0x28a
gopkg.in/doug-martin/goqu%2ev4.CrudExec.ScanStruct(0x16cce80, 0xc420268960, 0x165a5cf, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15af4c0, ...)
	/Users/charlie/Source/gopath/src/gopkg.in/doug-martin/goqu.v4/crud_exec.go:92 +0xcb
gopkg.in/doug-martin/goqu%2ev4.(*crudExecTest).TestScanStruct(0xc420116d60)
	/Users/charlie/Source/gopath/src/gopkg.in/doug-martin/goqu.v4/crud_exec_test.go:221 +0x1509
reflect.Value.call(0xc4203d6a20, 0xc4200acad0, 0x13, 0x1654c2f, 0x4, 0xc420040f50, 0x1, 0x1, 0x1649ee0, 0xc420116d60, ...)
	/usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:447 +0xa92
reflect.Value.Call(0xc4203d6a20, 0xc4200acad0, 0x13, 0xc420040f50, 0x1, 0x1, 0xf, 0x106969b, 0x1009b20)
	/usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:308 +0xc1
gopkg.in/doug-martin/goqu.v4/vendor/github.com/c2fo/testify/suite.Run.func2(0xc42012e3c0)
	/Users/charlie/Source/gopath/src/gopkg.in/doug-martin/goqu.v4/vendor/github.com/c2fo/testify/suite/suite.go:94 +0x1ff
testing.tRunner(0xc42012e3c0, 0xc420424b60)
	/usr/local/Cellar/go/1.10.3/libexec/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/usr/local/Cellar/go/1.10.3/libexec/src/testing/testing.go:824 +0x565
FAIL	gopkg.in/doug-martin/goqu.v4	0.044s
```

**Comment by halfcrazy** [comment]
https://github.com/doug-martin/goqu/compare/master...halfcrazy:update-go-version

> reflect: reflect.Value.Set using value obtained using unexported field 

You can not use a unexpoted field. Change name to upper case will resolve the problem.
